export const FETCH_PET_DETAIL = 'FETCH_PET_DETAIL';
export const FETCH_PET_DETAIL_FULFILLED = 'FETCH_PET_DETAIL_FULFILLED';
export const FETCH_PET_DETAIL_REJECTED = 'FETCH_PET_DETAIL_REJECTED';
export const FETCH_PETS = 'FETCH_PETS';
export const FETCH_PETS_FULFILLED = 'FETCH_PETS_FULFILLED';
export const FETCH_PETS_REJECTED = 'FETCH_PETS_REJECTED';